services:
  - type: web
    name: plant-disease-api
    runtime: python
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: python main.py
    repo: https://github.com/SazzHub221/Plant-Disease-Detection.git
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 10000
    healthCheckPath: /ping
    autoDeploy: true
    buildFilter:
      paths:
        - api/**